### ISSUE TITLE
Tooltip (info window) stays on the screen

### ISSUE THREAD

**Issue by abakirov** [Esri/cedar#144]
Steps:
1. Go to http://esri.github.io/cedar/examples/bar.html
2. Hold mouse over the last bar
3. Swiftly move mouse out to the right
4. Popup stays on the screen
![image](https://cloud.githubusercontent.com/assets/5304673/8778738/5ae7e25c-2eb4-11e5-9a70-461c214c7fbf.png)

It is somewhat difficult to repro in the above example, but it becomes quite annoying when charts are smaller and there are a couple of them: I simply move the mouse around and tooltips got stuck on the screen:
![image](https://cloud.githubusercontent.com/assets/5304673/8778799/acbdcec0-2eb4-11e5-8560-56d70285bd59.png)

**Comment by asizer** [comment]
more consistent repro:
in step 3, instead of swiftly moving mouse to the right, keep the mouse cursor on the tooltip as you move it to the right. once the cursor is out of the chart area, the tooltip is stuck until the mouse returns to the chart area.

Easy to repro on any tooltip that sticks outside the chart area, not just the last bar.

A slightly different thing happens (though less consistently) when a tooltip is visible and the user quickly scrolls down so the cursor is outside the chart area. Probably the same issue. Screenshot: 

<img width="500" alt="screen shot 2015-07-29 at 1 19 08 pm" src="https://cloud.githubusercontent.com/assets/1692781/8964797/a4e0357e-35f5-11e5-8ec0-89463a2547ca.png">

**Comment by ajturner** [comment]
Thanks @asizer 

This should be an easy fix - need to check on the events to clear when mouse out
