### ISSUE TITLE
inline data & local cedar.js import problem

### ISSUE THREAD

**Issue by azhigimont** [Esri/cedar#151]
I have a weird problem with the standard Cedar example for inline data with the bar chart.
If I import *cedar.js* from disk (vs from github.io) the example fails because in the Vega script:

prototype.insert = function(tuples) {
  var prev = this._revises ? null : undefined;
  var insert = tuples.map(function(d) {
    return Tuple.ingest(d, prev);
  });

**tuples** is the whole JSON data oblect from *feature-collection-data.json* and the call to **map** fails.
If I import *cedar.js* as http://esri.github.io/cedar/js/cedar.js **tuples** is just a list of features and everything works fine. D3 and Vega are imported from disk or remotely without problems.

**Comment by ajturner** [comment]
@azhigimont are you pointing to Master or Develop? `http://esri.github.io/cedar/js/cedar.js` is served from Develop right now.

**Comment by azhigimont** [comment]
I tried with both http://esri.github.io/cedar/js/cedar.js and https://rawgit.com/Esri/cedar/master/src/cedar.js. They both expose the aforementioned behavior when imported from disk.

**Comment by azhigimont** [comment]
Actually, https://rawgit.com/Esri/cedar/master/src/cedar.js have the same problem with remote import. I'm utterly confused.

**Comment by ajturner** [comment]
@azhigimont  an example would help tremendously to understand how the error is occurring. Can you provide one?

**Comment by ajturner** [comment]
the issue was @azhigimont was using an out of date bar.json. Specifically it was missing `data.format.property = "features"`

the [hosted bar.json](http://esri.github.io/cedar/js/charts/bar.json) has the correct format.

in the future plan to remove this ArcGIS flavoring and have Cedar.js handle vanilla data arrays or Feature Service nested responses transparently to the dev.
