### ISSUE TITLE
Support AMD

### ISSUE THREAD

**Issue by abakirov** [Esri/cedar#63]
Currently, Cedar expects global `vg` variable but in presence of an AMD loader (e.g. Esri JS API), Vega defines itself as AMD module without creating global variables. Cedar fails to work in this scenario.

**Comment by tomwayson** [comment]
This was resolved by #94 however, I think it's a good idea to modify the JSAPI map examples below to require Cedar via AMD instead of using the global:

http://esri.github.io/cedar/examples/bar-map-integration.html
http://esri.github.io/cedar/examples/filter-chart-by-map-extent.html
http://esri.github.io/cedar/examples/filter-chart-by-bbox.html
http://esri.github.io/cedar/examples/map-to-chart-interaction.html
http://esri.github.io/cedar/examples/complex-map-multiple-chart.html

I can create an AMD header template that defines dojo packages for Cedar, Vega, and D3 based on [this gist](https://gist.github.com/tomwayson/8ea426069e639886682c) and use that for the above samples instead of the current header template which pulls in Cedar as a global.

**Comment by ajturner** [comment]
Agreed - the samples using the JSAPI should use the Cedar in AMD.

**Comment by tomwayson** [comment]
resolved by #94 and #98
